//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ressource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous créer un nouveau fichier de backup et donc supprimer l&apos;ancien fichier ?.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chubb.
        /// </summary>
        public static string Chubb {
            get {
                return ResourceManager.GetString("Chubb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAS.
        /// </summary>
        public static string DAS {
            get {
                return ResourceManager.GetString("DAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEF.
        /// </summary>
        public static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DI.
        /// </summary>
        public static string DI {
            get {
                return ResourceManager.GetString("DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez séléctionner une application valide!.
        /// </summary>
        public static string Eappvalide {
            get {
                return ResourceManager.GetString("Eappvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à une erreur est survenue avec l&apos;ouverture du fichier Autocad.
        /// </summary>
        public static string EAutocad {
            get {
                return ResourceManager.GetString("EAutocad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à une erreur est survenue avec l&apos;ouverture du fichier Configuration 1.
        /// </summary>
        public static string EConf1 {
            get {
                return ResourceManager.GetString("EConf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à une erreur est survenue avec l&apos;ouverture du fichier Configuration 2.
        /// </summary>
        public static string EConf2 {
            get {
                return ResourceManager.GetString("EConf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DAS DEF.
        /// </summary>
        public static string EDASChubb {
            get {
                return ResourceManager.GetString("EDASChubb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DAS DEF.
        /// </summary>
        public static string EDASDEF {
            get {
                return ResourceManager.GetString("EDASDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DAS Esser.
        /// </summary>
        public static string EDASEsser {
            get {
                return ResourceManager.GetString("EDASEsser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DAS Siemens.
        /// </summary>
        public static string EDASSiemens {
            get {
                return ResourceManager.GetString("EDASSiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DI Chubb.
        /// </summary>
        public static string EDIChubb {
            get {
                return ResourceManager.GetString("EDIChubb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DI DEF.
        /// </summary>
        public static string EDIDEF {
            get {
                return ResourceManager.GetString("EDIDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DI Esser.
        /// </summary>
        public static string EDIEsser {
            get {
                return ResourceManager.GetString("EDIEsser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DI Finsecur.
        /// </summary>
        public static string EDIFinsecur {
            get {
                return ResourceManager.GetString("EDIFinsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du DI Siemens.
        /// </summary>
        public static string EDISiemens {
            get {
                return ResourceManager.GetString("EDISiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec l&apos;ouverture du fichier.
        /// </summary>
        public static string Efile {
            get {
                return ResourceManager.GetString("Efile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction.
        /// </summary>
        public static string EFoncChubb {
            get {
                return ResourceManager.GetString("EFoncChubb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction DEF.
        /// </summary>
        public static string EFoncDEF {
            get {
                return ResourceManager.GetString("EFoncDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du Fct Esser.
        /// </summary>
        public static string EFoncEsser {
            get {
                return ResourceManager.GetString("EFoncEsser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction Finsecur.
        /// </summary>
        public static string EFoncFinsecur {
            get {
                return ResourceManager.GetString("EFoncFinsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction Siemens.
        /// </summary>
        public static string EfoncSiemens {
            get {
                return ResourceManager.GetString("EfoncSiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération du MDLO Finsecur.
        /// </summary>
        public static string EMDLOFinsecur {
            get {
                return ResourceManager.GetString("EMDLOFinsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner un nombre.
        /// </summary>
        public static string Enb {
            get {
                return ResourceManager.GetString("Enb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Esser.
        /// </summary>
        public static string Esser {
            get {
                return ResourceManager.GetString("Esser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction UGA DEF.
        /// </summary>
        public static string EUGADEF {
            get {
                return ResourceManager.GetString("EUGADEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction UGA Finsecur.
        /// </summary>
        public static string EUGAFinsecur {
            get {
                return ResourceManager.GetString("EUGAFinsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la fonction UGA Siemens.
        /// </summary>
        public static string EUGASiemens {
            get {
                return ResourceManager.GetString("EUGASiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue avec la génération de la voie Finsecur.
        /// </summary>
        public static string EVoieFinsecur {
            get {
                return ResourceManager.GetString("EVoieFinsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finsecur.
        /// </summary>
        public static string Finsecur {
            get {
                return ResourceManager.GetString("Finsecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonction.
        /// </summary>
        public static string Fonc {
            get {
                return ResourceManager.GetString("Fonc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers bien importer!.
        /// </summary>
        public static string importok {
            get {
                return ResourceManager.GetString("importok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MDLO.
        /// </summary>
        public static string MDLO {
            get {
                return ResourceManager.GetString("MDLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NO.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panorama.
        /// </summary>
        public static string Panorama {
            get {
                return ResourceManager.GetString("Panorama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PcVue.
        /// </summary>
        public static string PcVue {
            get {
                return ResourceManager.GetString("PcVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séléctioné le fichier a mettre à jours!.
        /// </summary>
        public static string SelMAJ {
            get {
                return ResourceManager.GetString("SelMAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Siemens.
        /// </summary>
        public static string Siemens {
            get {
                return ResourceManager.GetString("Siemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UGA.
        /// </summary>
        public static string uga {
            get {
                return ResourceManager.GetString("uga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voie.
        /// </summary>
        public static string Voie {
            get {
                return ResourceManager.GetString("Voie", resourceCulture);
            }
        }
    }
}
